overwrite: true
schema:
  - "http://localhost:3000/api/v1" 
documents:
  - "./src/graphql/**/*.graphql"
  - "./src/**/*.ts"
generates:
  ./src/graphql/__generated__/graphql.ts:
    config:
      useIndexSignature: true
      contextType: "../context/index#GraphQLContext"
      mapperTypeSuffix: Model
      mappers:
        User: "@prisma/client#User"
        Member: "@prisma/client#Member"
    plugins:
      - typescript
      - typescript-operations
      - typescript-react-apollo
      - typescript-resolvers