overwrite: true
schema:
  - "http://localhost:3000/api/v1" 
documents:
  - "./src/graphql/**/*.graphql"
  - "./src/graphql/**/*.ts"
generates:
  ./src/graphql/__generated__/graphql.ts:
    config:
      useIndexSignature: true
      contextType: "../context/index#GraphQLContext"
      mapperTypeSuffix: Model
      mappers:
        User: "@prisma/client#User"
        Member: "@prisma/client#Member"
        Blog: "@prisma/client#Blog"
        Tag: "@prisma/client#Tag"
        Payment: "@prisma/client#Payment"
        Dues: "@prisma/client#Dues"
        Event: "@prisma/client#Event"
        EventResource: "@prisma/client#EventResource"
        EventRegistration: "@prisma/client#EventRegistration"
    plugins:
      - typescript
      - typescript-operations
      - typescript-react-apollo
      - typescript-resolvers