import { Resolvers } from "@/graphql/__generated__/graphql";
import GraphQLJSON from 'graphql-type-json';

export const resolvers: Resolvers = {
    JSON: GraphQLJSON,
    Mutation: {
        createUser: (_, { input }, { prisma, dataSources }) => dataSources.userAPI.addUser(prisma, input),
        login: (_, { input }, { prisma, dataSources }) => dataSources.userAPI.loginUser(prisma, input),
        createDue: (_, { input }, { prisma, dataSources, userId }) => dataSources.dueAPI.createDue(prisma, input, userId),
        postPayment: (_, { input }, { prisma, dataSources }) => dataSources.paymentAPI.postPayment(prisma, input),
        deactivateMember: (_, { memberId, status }, { prisma, dataSources }) => dataSources.memberAPI.deactivate(prisma, memberId, status),
        createBlog: (_, { input }, { prisma, dataSources, userId }) => dataSources.blogAPI.createBlog(prisma, userId, input),
        publishedBlog: (_, { blogId, status }, { prisma, dataSources }) => dataSources.blogAPI.publishedBlog(prisma, blogId, status),
        createEvent: (_, { input }, { prisma, dataSources }) => dataSources.eventAPI.createEvent(prisma, input),
        watchEventViews: (_, {eventId}, {prisma, dataSources}) => dataSources.eventAPI.watchViews(prisma, eventId),
        cancelEvent: (_, {eventId, status}, {prisma, dataSources}) => dataSources.eventAPI.cancelEvent(prisma, eventId, status),
        deleteEvent: (_, {eventId}, {prisma, dataSources}) => dataSources.eventAPI.deleteEvent(prisma, eventId),
        archiveDue: (_, {dueId}, {prisma, dataSources}) => dataSources.dueAPI.archiveDue(prisma, dueId),
        updateDues: (_, {dueId, input}, {prisma, dataSources, userId}) => dataSources.dueAPI.updateDue(prisma, dueId, input, userId),
        postMultiPayment: (_, {input}, {prisma, dataSources}) => dataSources.paymentAPI.postMultiPayment(prisma, input),
        postEventRegistration: (_, {input}, {prisma, dataSources}) => dataSources.eventAPI.postRegistration(prisma, input),
        profilephotoUpload: (_, {memberId, photo}, {prisma, dataSources}) => dataSources.memberAPI.uploadPhoto(prisma, memberId, photo),
        resetPassword: (_, {userId, password}, {prisma, dataSources}) => dataSources.userAPI.resetPassword(prisma, userId, password),
        createResources: (_, {input}, {prisma, dataSources, userId}) => dataSources.resourceAPI.createResources(prisma, input, userId),
        deleteResource: (_, {resourceId}, {prisma, dataSources}) => dataSources.resourceAPI.deleteResource(prisma, resourceId),
        resendEventMail: (_, {input}, {prisma, dataSources}) => dataSources.eventAPI.resendEventMail(prisma, input),
    },
    Query: {
        members: (_, __, { prisma, dataSources, userId }) => dataSources.memberAPI.getMembers(prisma, userId),
        member: (_, { id }, { prisma, dataSources }) => dataSources.memberAPI.getMember(prisma, id),
        users: (_, __, { prisma, dataSources }) => dataSources.userAPI.getUsers(prisma),
        dues: (_, __, { prisma, dataSources }) => dataSources.dueAPI.getDues(prisma),
        singeDue: (_, { dueId }, { prisma, dataSources }) => dataSources.dueAPI.getDue(prisma, dueId),
        getPayments: (_, { memberId }, { prisma, dataSources }) => dataSources.paymentAPI.getPayments(prisma, memberId),
        getPayment: (_, { paymentId }, { prisma, dataSources }) => dataSources.paymentAPI.getPayment(prisma, paymentId),
        memberPayments: (_, { memberId }, { prisma, dataSources }) => dataSources.paymentAPI.memberPayments(prisma, memberId),
        getDuePayment: (_, { memberId }, { prisma, dataSources }) => dataSources.dueAPI.getDuePayment(prisma, memberId),
        getRecentRegistration: (_, __, { prisma, dataSources }) => dataSources.dashboardAPI.getRecentRegistrations(prisma),
        getBlogs: (_, { status }, { prisma, dataSources }) => dataSources.blogAPI.getBlogs(prisma, status),
        getBlog: (_, { blogId }, { prisma, dataSources }) => dataSources.blogAPI.getBlog(prisma, blogId),
        getEvents: (_, __, { prisma, dataSources }) => dataSources.eventAPI.getEvents(prisma),
        getEvent: (_, { eventId }, { prisma, dataSources }) => dataSources.eventAPI.getEvent(prisma, eventId),
        eventFormFields: (_, __, { prisma, dataSources }) => dataSources.eventAPI.getFormFields(prisma),
        getAdminDashboardStat: (_, __, {prisma, dataSources}) => dataSources.dashboardAPI.getAdminStat(prisma),
        getSidebarStat: (_, __, {prisma, dataSources}) => dataSources.dashboardAPI.getSidebarData(prisma),
        getMembersAttendance: (_, {eventId}, {prisma, dataSources}) => dataSources.eventAPI.getMembersAttendance(prisma, eventId),
        getRegisteredMembers: (_, {eventId}, {prisma, dataSources}) => dataSources.eventAPI.getRegisteredMembers(prisma, eventId),
        getEventsForPublic: (_, __, { prisma, dataSources }) => dataSources.eventAPI.getEventsForPublic(prisma),
        getUpComingEvents: (_, {memberId}, {prisma, dataSources}) => dataSources.eventAPI.upComingEvents(prisma, memberId),
        getPastEvents: (_, __, {prisma, dataSources}) => dataSources.eventAPI.passedEvents(prisma),
        getMemberStat: (_, {memberId}, {prisma, dataSources}) => dataSources.dashboardAPI.getMemberStat(prisma, memberId),
        getMemberUnpaidDues: (_, {memberId, membershipTypeId}, {prisma, dataSources}) => dataSources.dueAPI.getUnpaidDues(prisma, memberId, membershipTypeId),
        getMembershipTypes: (_, __, {prisma, dataSources}) => dataSources.userAPI.getMembershipTypes(prisma),
        getRegistrationForm: (_, {eventId}, {prisma, dataSources}) => dataSources.eventAPI.getRegistrationForm(prisma, eventId),
        getMember: (_, {memberId}, {prisma, dataSources}) => dataSources.memberAPI.getMember(prisma, memberId),
        getUser: (_, {userId}, {prisma, dataSources}) => dataSources.userAPI.getUser(prisma, userId),
        getResources: (_, __, {prisma, dataSources}) => dataSources.resourceAPI.getResources(prisma),
        getResource: (_, {resourceId}, {prisma, dataSources}) => dataSources.resourceAPI.getResource(prisma, resourceId),
        revenueByCategory: (_, {duration}, {prisma, dataSources}) => dataSources.dashboardAPI.revenueByCategory(prisma, duration)
    },
};